# Generated by Django 4.0 on 2022-01-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_family_character_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='members',
            new_name='family',
        ),
    ]
