# Generated by Django 4.0 on 2022-01-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_rename_members_character_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
