# Generated by Django 4.0 on 2022-01-11 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_rename_relations_character_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='generation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
    ]
